[package]
name = "demangle_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
msvc-demangler = "0.9"
libc = "0.2"

[lib]
name = "msvc_demangler"
crate-type = ["cdylib", "rlib"]

